### ISSUE TITLE
Potential blocking call in EmmitBatchAsync

### ISSUE THREAD

**Issue by CatalinAdlerDF** [manigandham/serilog-sinks-googlecloudlogging#53]
Hi,

I think the using on the StreamWriter will invoke the sync Dispose.
did not read the code thoroughly but shouldn't that method be normal async with proper awaits everywhere isntead?

**Comment by manigandham** [comment]
Hey @CatalinAdlerDF 
Are you referring to this? https://github.com/manigandham/serilog-sinks-googlecloudlogging/blob/master/src/Serilog.Sinks.GoogleCloudLogging/GoogleCloudLoggingSink.cs#L66

The `StringWriter` is a used to create the message for each log entry in the `CreateLogEntry` function below. The message strings and `List<LogEntry>` are assembled in memory so there's no need for async writing or disposing.

The [`WriteLogEntriesAsync`](https://github.com/manigandham/serilog-sinks-googlecloudlogging/blob/master/src/Serilog.Sinks.GoogleCloudLogging/GoogleCloudLoggingSink.cs#L72) method is responsible for actually writing out the messages to the logging output and it's being called asynchronously already. In this case, instead of using `await` for that, it's better to just return the `Task` itself and let the Serilog batch sink handle the await. That's why a [`Task.CompletedTask`](https://github.com/manigandham/serilog-sinks-googlecloudlogging/blob/master/src/Serilog.Sinks.GoogleCloudLogging/GoogleCloudLoggingSink.cs#L73) is returned when there are no messages to write. This is called async eliding and saves a level of async code and improves performance.

Stephen Clearly has a good blog post on that here: https://blog.stephencleary.com/2016/12/eliding-async-await.html

Hope that helps, let me know.

**Comment by manigandham** [comment]
Closing this now, feel free to reopen if you have more questions.

**Comment by CatalinAdlerDF** [comment]
Thanks for the answer!
I saw that TextWriter disposeasync is a no-op in the end so it just doesn't matter.

**Comment by manigandham** [comment]
Sure. To be clear, `TextWriter` is an abstract base class and is implemented by [`StringWriter`](https://docs.microsoft.com/en-us/dotnet/api/system.io.stringwriter) which writes to an internal `StringBuilder`. The `DisposeAsync` is called when using `await using` instead of the normal `using` and that's not needed here because the strings are built in-memory.
