### ISSUE TITLE
GKE no logs

### ISSUE THREAD

**Issue by adamzak1** [manigandham/serilog-sinks-googlecloudlogging#62]
Hi,
I have an application running in GCP GKE, and there are just no logs shown in google, 
tried play with/without project-id etc, same result , I have Log Writer permissions on the cluster, 
![image](https://user-images.githubusercontent.com/89729627/185348783-d4f1a96d-5143-4380-9dbb-4be83712d85f.png)

**Comment by manigandham** [comment]
Try using the Serilog SelfLog output to see if there are any exceptions being thrown:

https://github.com/serilog/serilog/wiki/Debugging-and-Diagnostics

**Comment by adamzak1** [comment]
hi,
got 
`Exception while emitting periodic batch from Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink: Grpc.Core.RpcException: Status(StatusCode="PermissionDenied", Detail="Permission 'logging.logEntries.create' denied on resource (or it may not exist).") at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass0_0`2.<<WithRetry>b__0>d.MoveNext()`
but I do have Log Writer permissions,
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/89729627/187024186-668cdcd9-ef2f-4eed-afc9-585bda10b2c4.png">

**Comment by manigandham** [comment]
If that's the error then it might be using the wrong service account. Check the service account being used. You can also manually configure it my adding the JSON credentials file to K8S as a secret, then deploying that inside your YAML spec.

Also if you're running in GCP already, then you can also just log to console and GKE will send those logs to GCP logging anyway - so that might work for you.
